spring.application.name=sistema
spring.datasource.url=jdbc:postgresql://189.90.66.154:5432/waldemarserafim
spring.datasource.username=waldemarserafim
spring.datasource.password=bd2026

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=feature_store